// <auto-generated />
using System;
using ExcelETL.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelETL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExcelEtlDbContext))]
    [Migration("20260710174749_AddCompletedAtUtcToExtractionHistories")]
    partial class AddCompletedAtUtcToExtractionHistories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelETL.Domain.Entities.CellMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SheetConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceCell")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetPropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SheetConfigId");

                    b.ToTable("CellMappings", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ExtractionConfigs", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("JobTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("ExtractionHistories", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExtractionConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionConfigId");

                    b.ToTable("SheetConfigs", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.CellMapping", b =>
                {
                    b.HasOne("ExcelETL.Domain.Entities.SheetConfig", null)
                        .WithMany("CellMappings")
                        .HasForeignKey("SheetConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.HasOne("ExcelETL.Domain.Entities.ExtractionConfig", null)
                        .WithMany("Sheets")
                        .HasForeignKey("ExtractionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionConfig", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.Navigation("CellMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
