// <auto-generated />
using System;
using ExcelETL.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelETL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExcelEtlDbContext))]
    [Migration("20260717113850_AddImportProfile")]
    partial class AddImportProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelETL.Domain.Entities.CellMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SheetConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceCell")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetPropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SheetConfigId");

                    b.ToTable("CellMappings", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ExtractionConfigs", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("JobTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("ExtractionHistories", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExtractionConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionConfigId");

                    b.ToTable("SheetConfigs", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Extraction.Profile.ImportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipementTypeElementNom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReperePrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ImportProfiles", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.CellMapping", b =>
                {
                    b.HasOne("ExcelETL.Domain.Entities.SheetConfig", null)
                        .WithMany("CellMappings")
                        .HasForeignKey("SheetConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.HasOne("ExcelETL.Domain.Entities.ExtractionConfig", null)
                        .WithMany("Sheets")
                        .HasForeignKey("ExtractionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExcelETL.Domain.Extraction.Profile.ImportProfile", b =>
                {
                    b.OwnsMany("ExcelETL.Domain.Extraction.Profile.SheetExtractionRule", "SheetRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ImportProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SheetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.PrimitiveCollection<string>("UnconditionalColonneNames")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ImportProfileId");

                            b1.ToTable("ImportProfileSheetRules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImportProfileId");

                            b1.OwnsMany("ExcelETL.Domain.Extraction.Primitives.ConditionalPointRule", "PointRules", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ColonneName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("ComparisonValue")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<int>("SheetExtractionRuleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("SourceFieldName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SheetExtractionRuleId");

                                    b2.ToTable("ImportProfileSheetRulePointRules", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SheetExtractionRuleId");
                                });

                            b1.OwnsOne("ExcelETL.Domain.Extraction.Primitives.RepeatingBlockLocator", "Locator", b2 =>
                                {
                                    b2.Property<int>("SheetExtractionRuleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FirstBlockStartRow")
                                        .HasColumnType("int")
                                        .HasColumnName("LocatorFirstBlockStartRow");

                                    b2.Property<string>("Sheet")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("LocatorSheet");

                                    b2.Property<int>("Step")
                                        .HasColumnType("int")
                                        .HasColumnName("LocatorStep");

                                    b2.Property<string>("StopFieldName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("LocatorStopFieldName");

                                    b2.HasKey("SheetExtractionRuleId");

                                    b2.ToTable("ImportProfileSheetRules");

                                    b2.WithOwner()
                                        .HasForeignKey("SheetExtractionRuleId");

                                    b2.OwnsMany("ExcelETL.Domain.Extraction.Primitives.BlockFieldDefinition", "Fields", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("ColumnRange")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("nvarchar(20)");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.Property<int>("RowOffsetEnd")
                                                .HasColumnType("int");

                                            b3.Property<int>("RowOffsetStart")
                                                .HasColumnType("int");

                                            b3.Property<int>("SheetExtractionRuleId")
                                                .HasColumnType("int");

                                            b3.HasKey("Id");

                                            b3.HasIndex("SheetExtractionRuleId");

                                            b3.ToTable("ImportProfileSheetRuleBlockFields", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("SheetExtractionRuleId");
                                        });

                                    b2.Navigation("Fields");
                                });

                            b1.Navigation("Locator")
                                .IsRequired();

                            b1.Navigation("PointRules");
                        });

                    b.Navigation("SheetRules");
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.ExtractionConfig", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("ExcelETL.Domain.Entities.SheetConfig", b =>
                {
                    b.Navigation("CellMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
