// <auto-generated />
using System;
using ExcelETL.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelETL.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExcelEtlDbContext))]
    [Migration("20260725010636_AddGeneratedFileRecord")]
    partial class AddGeneratedFileRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExcelETL.Domain.Archiving.GeneratedFileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EquipementRepere")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ExportProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("TargetFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementRepere");

                    b.HasIndex("GeneratedAtUtc");

                    b.ToTable("GeneratedFileRecords", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Extraction.Profile.ImportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("DefaultApplicationNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DefaultTableaux")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipementTypeElementNom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ReperePrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ImportProfiles", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Generation.Profile.ExportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExportProfiles", (string)null);
                });

            modelBuilder.Entity("ExcelETL.Domain.Extraction.Profile.ImportProfile", b =>
                {
                    b.OwnsMany("ExcelETL.Domain.Extraction.Profile.SheetExtractionRule", "SheetRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ImportProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SheetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.PrimitiveCollection<string>("UnconditionalColonneNames")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("ImportProfileId");

                            b1.ToTable("ImportProfileSheetRules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImportProfileId");

                            b1.OwnsMany("ExcelETL.Domain.Extraction.Primitives.ConditionalPointRule", "PointRules", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ColonneName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("ComparisonValue")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("Operator")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<int>("SheetExtractionRuleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("SourceFieldName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SheetExtractionRuleId");

                                    b2.ToTable("ImportProfileSheetRulePointRules", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SheetExtractionRuleId");
                                });

                            b1.OwnsOne("ExcelETL.Domain.Extraction.Primitives.RepeatingBlockLocator", "Locator", b2 =>
                                {
                                    b2.Property<int>("SheetExtractionRuleId")
                                        .HasColumnType("int");

                                    b2.Property<int>("FirstBlockStartRow")
                                        .HasColumnType("int")
                                        .HasColumnName("LocatorFirstBlockStartRow");

                                    b2.Property<string>("Sheet")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("LocatorSheet");

                                    b2.Property<int>("Step")
                                        .HasColumnType("int")
                                        .HasColumnName("LocatorStep");

                                    b2.Property<string>("StopFieldName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("LocatorStopFieldName");

                                    b2.HasKey("SheetExtractionRuleId");

                                    b2.ToTable("ImportProfileSheetRules");

                                    b2.WithOwner()
                                        .HasForeignKey("SheetExtractionRuleId");

                                    b2.OwnsMany("ExcelETL.Domain.Extraction.Primitives.BlockFieldDefinition", "Fields", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("ColumnRange")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("nvarchar(20)");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("nvarchar(200)");

                                            b3.Property<int>("RowOffsetEnd")
                                                .HasColumnType("int");

                                            b3.Property<int>("RowOffsetStart")
                                                .HasColumnType("int");

                                            b3.Property<int>("SheetExtractionRuleId")
                                                .HasColumnType("int");

                                            b3.HasKey("Id");

                                            b3.HasIndex("SheetExtractionRuleId");

                                            b3.ToTable("ImportProfileSheetRuleBlockFields", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("SheetExtractionRuleId");
                                        });

                                    b2.Navigation("Fields");
                                });

                            b1.Navigation("Locator")
                                .IsRequired();

                            b1.Navigation("PointRules");
                        });

                    b.Navigation("SheetRules");
                });

            modelBuilder.Entity("ExcelETL.Domain.Generation.Profile.ExportProfile", b =>
                {
                    b.OwnsMany("ExcelETL.Domain.Generation.Profile.SheetGenerationRule", "SheetRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ExportProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PivotSource")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("SheetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("Id");

                            b1.HasIndex("ExportProfileId");

                            b1.ToTable("ExportProfileSheetRules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExportProfileId");

                            b1.OwnsMany("ExcelETL.Domain.Generation.Profile.ApplicationColumnDefinition", "ApplicationColumnDefinitions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ApplicationNom")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("Header")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("MarkValue")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<int>("SheetGenerationRuleId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SheetGenerationRuleId");

                                    b2.ToTable("ExportProfileSheetRuleApplicationColumnDefinitions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SheetGenerationRuleId");
                                });

                            b1.OwnsMany("ExcelETL.Domain.Generation.Profile.ColumnDefinition", "ColumnDefinitions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Header")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<int>("SheetGenerationRuleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Source")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SheetGenerationRuleId");

                                    b2.ToTable("ExportProfileSheetRuleColumnDefinitions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SheetGenerationRuleId");
                                });

                            b1.OwnsMany("ExcelETL.Domain.Generation.Profile.PointColumnDefinition", "PointColumnDefinitions", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("ColonneNom")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("Header")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("MarkValue")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<int>("SheetGenerationRuleId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("SheetGenerationRuleId");

                                    b2.ToTable("ExportProfileSheetRulePointColumnDefinitions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SheetGenerationRuleId");
                                });

                            b1.Navigation("ApplicationColumnDefinitions");

                            b1.Navigation("ColumnDefinitions");

                            b1.Navigation("PointColumnDefinitions");
                        });

                    b.Navigation("SheetRules");
                });
#pragma warning restore 612, 618
        }
    }
}
