namespace ExcelETL.Domain.Exceptions;

// One member per distinct validation/business-rule failure raised by the Domain layer. Each name
// doubles as the resource key that ExcelETL.Application.Resources.DomainErrorMessages uses to
// translate it at the WebAPI/BlazorAdmin boundary -- see the DomainValidationException family.
public enum DomainErrorCode
{
    CellMapping_InvalidSourceCell,
    CellMapping_EmptyTargetPropertyName,
    SheetConfig_EmptySheetName,
    SheetConfig_NegativeSheetIndex,
    SheetConfig_DuplicateCellMapping,
    ExtractionConfig_EmptyName,
    ExtractionConfig_TooManySheets,
    ExtractionConfig_DuplicateSheetIndex,
    ExtractionHistory_EmptySourceFileName,
    ExtractionHistory_EmptyStoredFilePath,
    ExtractionHistory_CannotCompleteFromStatus,
    ExtractionHistory_CannotFailFromStatus,
    DirectCell_EmptySheet,
    DirectCell_InvalidRange,
    BlockFieldDefinition_EmptyName,
    BlockFieldDefinition_InvalidColumnRange,
    BlockFieldDefinition_RowOffsetEndBeforeStart,
    RepeatingBlockLocator_EmptySheet,
    RepeatingBlockLocator_NonPositiveFirstBlockStartRow,
    RepeatingBlockLocator_NonPositiveStep,
    RepeatingBlockLocator_EmptyStopFieldName,
    RepeatingBlockLocator_EmptyFields,
    SubstringAfter_EmptyPrefix,
    Concat_EmptyParts,
    FieldRef_EmptyFieldName,
    ConditionalPointRule_EmptySourceFieldName,
    ConditionalPointRule_EmptyComparisonValue,
    ConditionalPointRule_EmptyColonneName,
    EquipementPivot_EmptyRepere,
    EquipementPivot_EmptyDesignation,
    EquipementPivot_EmptyTypeElementNom,
    IsolementPivot_EmptyRepere,
    IsolementPivot_EmptyTypeElementNom,
    PointPivot_EmptyColonneNom,
    PointPivot_EmptyParentRepere,
    TacheMultiplePivot_EmptyAction,
    ExtractionError_EmptySheet,
    ExtractionError_EmptyBlockIdentifier,
    ExtractionError_EmptyMessage,
    ImportProfile_EmptyName,
    ImportProfile_EmptyReperePrefix,
    ImportProfile_EmptyEquipementTypeElementNom,
    ImportProfile_NoSheetRules,
    SheetExtractionRule_EmptySheetName,
    SheetExtractionRule_SheetNameLocatorMismatch,
    ExportProfile_EmptyName,
    ExportProfile_NoSheetRules,
    SheetGenerationRule_EmptySheetName,
    SheetGenerationRule_DuplicateHeader,
    SheetGenerationRule_DuplicateColonneNom,
    SheetGenerationRule_ColumnSourceIncompatibleWithPivotSource,
    ColumnDefinition_EmptyHeader,
    PointColumnDefinition_EmptyHeader,
    PointColumnDefinition_EmptyColonneNom,
    PointColumnDefinition_EmptyMarkValue
}
